// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeullrjvxxdweldihwbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpldWxscmp2eHhkd2VsZGlod2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMTk4ODQsImV4cCI6MjA1NTc5NTg4NH0.76xBJGRAp38mGPsoEKzk_NXY27pZo6m1y9HJW42xXQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);